// Data Store & Initial Listings for FinnMarket (Finn.no Architecture)

const INITIAL_CATEGORIES = [
    { id: 'all', name: 'جميع الأقسام', icon: 'fa-globe', badgeColor: '#475569' },
    { id: 'real_estate', name: 'العقارات', icon: 'fa-house-chimney', badgeColor: '#0284c7' },
    { id: 'vehicles', name: 'السيارات', icon: 'fa-car', badgeColor: '#2563eb' },
    { id: 'contracting', name: 'المقاولات والبناء', icon: 'fa-helmet-safety', badgeColor: '#b45309' },
    { id: 'services', name: 'الخدمات والأعمال', icon: 'fa-handshake-angle', badgeColor: '#8b5cf6' },
    { id: 'furniture', name: 'الأثاث والديكور', icon: 'fa-couch', badgeColor: '#9333ea' },
    { id: 'electronics', name: 'الأجهزة والإلكترونيات', icon: 'fa-tv', badgeColor: '#4f46e5' },
    { id: 'phones', name: 'الجوالات والحواسيب', icon: 'fa-mobile-screen-button', badgeColor: '#0f766e' },
    { id: 'home_garden', name: 'المنزل والحديقة', icon: 'fa-seedling', badgeColor: '#15803d' },
    { id: 'marketplace', name: 'السوق العام والمستعمل', icon: 'fa-store', badgeColor: '#64748b' },
    { id: 'jobs', name: 'الوظائف', icon: 'fa-briefcase', badgeColor: '#d97706' },
    { id: 'education', name: 'التعليم والتدريب', icon: 'fa-graduation-cap', badgeColor: '#0369a1' },
    { id: 'pets', name: 'الحيوانات ومستلزماتها', icon: 'fa-paw', badgeColor: '#be185d' },
    { id: 'freebies', name: 'إهداء مجاني', icon: 'fa-gift', badgeColor: '#059669' },
    { id: 'boats', name: 'القوارب والبحري', icon: 'fa-ship', badgeColor: '#06b6d4' },
    { id: 'motorbikes', name: 'الدراجات والمحركات', icon: 'fa-motorcycle', badgeColor: '#ec4899' }
];

const INITIAL_CITIES = [
    'جميع المدن',
    // منطقة الرياض
    'الرياض',
    'الدرعية',
    'الخرج',
    'الدوادمي',
    'المجمعة',
    'القويعية',
    'وادي الدواسر',
    'الأفلاج',
    'الزلفي',
    'شقراء',
    'حوطة بني تميم',
    'عفيف',
    'السليل',
    'ضرما',
    'المزاحمية',
    'رماح',
    'ثادق',
    'حريملاء',
    'الحريق',
    'الغاط',
    'مرات',
    // منطقة مكة المكرمة
    'جدة',
    'مكة المكرمة',
    'الطائف',
    'القنفذة',
    'الليث',
    'رابغ',
    'الجموم',
    'خليص',
    'الكامل',
    'الخرمة',
    'رنية',
    'تربة',
    'ميسان',
    'أضم',
    'العرضيات',
    'بحرة',
    // منطقة المدينة المنورة
    'المدينة المنورة',
    'ينبع',
    'العلا',
    'المهد',
    'الحناكية',
    'بدر',
    'خيبر',
    'العيص',
    // المنطقة الشرقية
    'الدمام',
    'الخبر',
    'الظهران',
    'الأحساء (الهفوف)',
    'الجبيل',
    'حفر الباطن',
    'القطيف',
    'رأس تنورة',
    'بقيق',
    'الخفجي',
    'النعيرية',
    'قرية العليا',
    // منطقة القصيم
    'بريدة (القصيم)',
    'عنيزة',
    'الرس',
    'المذنب',
    'البكيرية',
    'البدائع',
    'الأسياح',
    'النبهانية',
    'رياض الخبراء',
    'عيون الجواء',
    'الشماسية',
    'عقلة الصقور',
    'ضرية',
    // منطقة حائل
    'حائل',
    'بقعاء',
    'الغزالة',
    'الشنان',
    'موقق',
    'الحائط',
    'الشملي',
    'السليمي',
    'سميراء',
    // منطقة تبوك
    'تبوك',
    'ضباء',
    'الوجه',
    'أملج',
    'تيماء',
    'حقل',
    'البدع',
    // منطقة عسير
    'أبها',
    'خميس مشيط',
    'بيشة',
    'محايل عسير',
    'النماص',
    'أحد رفيدة',
    'بارق',
    'البرك',
    'بلقرن',
    'تثليث',
    'تنومة',
    'رجال ألمع',
    'سراة عبيدة',
    'ظهران الجنوب',
    'المجاردة',
    'طريب',
    'الحرجة',
    // منطقة جازان
    'جازان',
    'صبيا',
    'أبو عريش',
    'صامطة',
    'بيش',
    'الدرب',
    'ضمد',
    'أحد المسارحة',
    'العارضة',
    'العيدابي',
    'فيفا',
    'هروب',
    'الريث',
    'فرسان',
    'الطوال',
    'الحرث',
    // منطقة نجران
    'نجران',
    'شرورة',
    'حبونا',
    'بدر الجنوب',
    'يدمة',
    'ثار',
    'خباش',
    // منطقة الباحة
    'الباحة',
    'بلجرشي',
    'المندق',
    'المخواة',
    'قلوة',
    'العقيق',
    'القرى',
    'الحجرة',
    'غامد الزناد',
    // منطقة الحدود الشمالية
    'عرعر',
    'رفحاء',
    'طريف',
    'العويقيلة',
    // منطقة الجوف
    'سكاكا (الجوف)',
    'دومة الجندل',
    'القريات',
    'طبرجل',
    // دول الخليج
    'دبي',
    'أبوظبي',
    'الكويت',
    'الدوحة',
    'المنامة',
    'مسقط'
];

const MOCK_LISTINGS = [
    {
        id: 'list-101',
        title: 'فيلا مودرن فاخرة مع مسبح وحديقة خاصة',
        category: 'real_estate',
        subCategory: 'فلل للبيع',
        price: 2450000,
        isFree: false,
        city: 'الرياض',
        neighborhood: 'حي حطين',
        condition: 'new',
        timeAgo: 'منذ ساعتين',
        views: 342,
        favoritesCount: 28,
        images: [
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'
        ],
        seller: {
            name: 'شركة قمة العقارية',
            avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
            phone: '+966 50 123 4567',
            rating: 4.9,
            ratingCount: 18,
            verified: true
        },
        specs: {
            'المساحة': '450 م²',
            'عدد الغرف': '6 غرف نوم',
            'الدورات': '5 حمامات',
            'عمر العقار': 'جديد (2026)'
        },
        description: 'فيلا مودرن للبيع في أرقى أحياء الرياض، تصميم عصري هندسي متميز بمسطحات بناء واسعة، مسبح تدفئة، تكييف مخفي بالكامل، ضمانات شاملة.',
        comments: [
            {
                id: 'cm-1',
                author: 'خالد المطيري',
                avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
                isSeller: false,
                isMember: true,
                text: 'ما شاء الله تبارك الله، هل السعر قابل للتفاوض البسيط للصادق؟',
                time: 'منذ ساعتين'
            }
        ]
    },
    {
        id: 'list-102',
        title: 'تويوتا كامري 2024 GLE بنزين - حالة الوكالة',
        category: 'vehicles',
        subCategory: 'سيارات سيدان',
        price: 98000,
        isFree: false,
        city: 'جدة',
        neighborhood: 'حي الشاطئ',
        condition: 'like_new',
        timeAgo: 'منذ 3 ساعات',
        views: 512,
        favoritesCount: 41,
        images: [
            'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80'
        ],
        seller: {
            name: 'فهد العتيبي',
            avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
            phone: '+966 55 987 6543',
            rating: 4.8,
            ratingCount: 12,
            verified: true
        },
        specs: {
            'سنة الصنع': '2024',
            'الممشى': '15,000 كم',
            'الناقل': 'أوتوماتيك'
        },
        description: 'سيارة تويوتا كامري فل كامل GLE خالية من الحوادث والصدمات، صيانة دورية بالوكالة.',
        comments: []
    },
    {
        id: 'list-109',
        title: 'يخت نزهة فاخر 38 قدم مع محركين ياماها',
        category: 'boats',
        subCategory: 'قوارب ويخوت',
        price: 185000,
        isFree: false,
        city: 'جدة',
        neighborhood: 'مرسى الأحلام',
        condition: 'good',
        timeAgo: 'منذ 4 ساعات',
        views: 310,
        favoritesCount: 22,
        images: [
            'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1200&q=80'
        ],
        seller: {
            name: 'الكابتن طارق البحراني',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
            phone: '+966 54 888 9900',
            rating: 5.0,
            ratingCount: 9,
            verified: true
        },
        specs: {
            'الطول': '38 قدم',
            'المحركات': '2 x Yamaha 250HP',
            'الحمولة': '12 شخص'
        },
        description: 'قارب نزهة وغوص متكامل، تكييف، غرفة نوم، شاور، نظام ملاحة حديث وتصريح نزهة جاهز.',
        comments: []
    },
    {
        id: 'list-110',
        title: 'دراجة نارية هارلي ديفيدسون سبرينجر موديل 2023',
        category: 'motorbikes',
        subCategory: 'دراجات نارية',
        price: 74000,
        isFree: false,
        city: 'الرياض',
        neighborhood: 'حي السليمانية',
        condition: 'like_new',
        timeAgo: 'منذ 5 ساعات',
        views: 420,
        favoritesCount: 31,
        images: [
            'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80'
        ],
        seller: {
            name: 'سعود الهاجري',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
            phone: '+966 50 444 1122',
            rating: 4.9,
            ratingCount: 15,
            verified: true
        },
        specs: {
            'الموديل': '2023',
            'المحرك': '114 ci',
            'الممشى': '3,500 كم'
        },
        description: 'هارلي ديفيدسون بحالة الوكالة مع اكسسوارات أصلية وعادم كروم ومفتاحين ذكيين.',
        comments: []
    }
];
